# Site settings
title: HIMMEL
email: lazing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  关注中文互联网
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.2byte.us" # the base hostname & protocol for your site
twitter_username: lazing
github_username:  lazing

# Build settings
markdown: kramdown
